### ISSUE TITLE
La typo web OCL ne s'affiche pas correctement

### ISSUE THREAD

**Issue by christellePerrin** [christellePerrin/Cannes#3]

**Comment by christellePerrin** [comment]
Problème pour téléverser des images lourdes de 3,5 mo (pourtant dans la limite des 10mo)

**Comment by jeremien** [comment]
il faut que tu copies les fichiers de la font dans le dossier local public (public/fonts/ocl) à la racine, j'ai repris la feuille de style, ça devrait fonctionner

**Comment by jeremien** [comment]
cela vaut pour toutes les fonts en fait, même procédure, les styles pour importer sont dans _fonts.scss
